### ISSUE TITLE
Start menu icon gets smaller when plasma style enabled

### ISSUE THREAD

**Issue by claymorwan** [L4ki/Ars-Plasma-Themes#1]
For some reason, the Ars-Dark-Plasma style shrinks the start menu icon whenever I enable it
![image](https://github.com/user-attachments/assets/368b70d0-7b68-4427-b255-a90b8385a7c7)
without plasma style
![image](https://github.com/user-attachments/assets/de8595b6-11f7-463b-a0bf-a066d9cfd95f)
with plasma style

**Comment by L4ki** [comment]
Hi claymorwan, 

Thanks for your feedback. I'll fix it very quickly.

A few minutes ago I did update. Try now.

**Comment by claymorwan** [comment]
Oki I reinstalled the plasma style and it seems to be working now, Thanksu :3
