### ISSUE TITLE
Bug - Can't update Ars-Dark-Plasma

### ISSUE THREAD

**Issue by Y4k3d0** [L4ki/Ars-Plasma-Themes#3]
OS: Kubuntu noble 24.04 x86_64
Kernel: Linux 6.8.0-45-generic
DE: KDE Plasma 5.27.11
Current theme version: 1.7

Steps to reproduce : 
- Update to latest version from Discover (published 24/09/2024)

Error :
plamsa-themes.knsrc : Failed to install /tmp/OXlzmG-Ars-Dark-Plasma.tar.gz : The type of the new package is different from the type of the old version already installed.

All the other themes work just fine, it's just this one specifically.

**Comment by L4ki** [comment]
Hi Yakedo , 

I checked the plasma theme and everything is fine with her. 

I don't know what the cause is this mistake.

I recommend uninstalling theme and then reinstall it.

Greeting,

**Comment by Y4k3d0** [comment]
Nevermind, that did the trick. I'll try that from now on before reporting a bug.
Thank you for your time !
